name: Release Latest
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Build | Résumé
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./resume.tex

      - name: Build | Cirriculum Vitae
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./cv.tex

      - name: Build | Cover letter
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./coverletter.tex

      # Replace latest release
      - name: Clean | Latest
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
          tag_name: latest

      - name: Push | Latest
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Résumé, CV
          body: "The latest résumé, cirriculum vitae, and coverletter template from Spencer C. Imbleau."
          fail_on_unmatched_files: true
          draft: false
          files: |
            resume.pdf
            cv.pdf
            coverletter.pdf
