name: release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build résumé
      - name: Build résumé (latex)
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./resume/resume.tex

      # Build CV
      - name: Build CV (latex)
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./cv/cv.tex

      # Cache Coverletter
      - name: Cache Coverletter
        id: cache-coverletter
        uses: actions/cache@v3
        with:
          path: ./coverletter.pdf
          key: cv-${{ hashFiles('./coverletter') }}

      # Build Coverletter
      - name: Build Coverletter (latex)
        if: steps.cache-coverletter.outputs.cache-hit != 'true'
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./coverletter/coverletter.tex

      # Upload PDFs
      - name: Upload PDFs
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            resume.pdf
            cv.pdf
            coverletter.pdf
