name: release-gh-pages

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Build | Résumé
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./resume.tex

      - name: Build | Cirriculum Vitae
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./cv.tex

      - name: Stage | PDFs
        run: mkdir pub/
          mv resume.pdf pub/
          mv cv.pdf pub/

      - name: Stage | Résumé, Index
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: ./templates/index.html.j2
          output_file: pub/index.html
        env:
          PDF: resume.pdf

      - name: Stage | Résumé, Embed
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: ./templates/embed.html.j2
          output_file: pub/embed.html
        env:
          PDF: resume.pdf

      - name: Stage | CV, Index
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: ./templates/index.html.j2
          output_file: pub/index.html
        env:
          PDF: cv.pdf

      - name: Stage | CV, Embed
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: ./templates/embed.html.j2
          output_file: pub/embed.html
        env:
          PDF: cv.pdf

      - name: Deploy, Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pub/
