name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache PDF
      - name: PDF Cache
        id: cache-pdf
        uses: actions/cache@v3
        with:
          path: ./aux/resume.pdf
          key: resume-${{ hashFiles('./src') }}

      # Build resume
      - name: Build source (latex)
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: ./src/resume.tex

      # Upload PDF
      - name: Upload PDF
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            resume.pdf
